#ifndef REDIS_RELEASE_H
#define REDIS_RELEASE_H

#define PROJECT_NAME     "@PROJECT_NAME@"
#define PROJECT_VERSION  "@PROJECT_VERSION@"
#define REDIS_GIT_SHA1   "@REDIS_GIT_SHA1@"
#define REDIS_GIT_DIRTY  "@REDIS_GIT_DIRTY@"
#define REDIS_BUILD_ID   "@HOSTNAME@-@TIMESTAMP@"

#endif // REDIS_RELEASE_H